language: java

sudo: false

install:
  - ./install-maven-dependencies.sh

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - '$HOME/.m2'

after_success:
  - bash <(curl -s https://codecov.io/bas)h
