language: java

sudo: false

install:
  - ./install-maven-dependencies.sh

os:
  - linux

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2'

after_success:
  - bash <(curl -s https://codecov.io/bash)
