language: java

sudo: false

install:
  - ./install-maven-dependencies.sh

os:
  - linux

jdk:
  - openjdk8

cache:
  directories:
    - '$HOME/.m2'

after_success:
  - curl "https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.2/codacy-coverage-reporter-2.0.2-assembly.jar" -o ~/codacy.coverage-reporter-2.0.2-assembly.jar
  - java -cp ~/codacy.coverage-reporter-2.0.2-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml --projectToken "${CODACY_PROJECT_TOKEN}"

